### ISSUE TITLE
How to indentify the introgression region

### ISSUE THREAD

**Issue by liufy11** [mmatschiner/tutorials#1]
Both SNP data and Chromosome-Length Alignments can test whether exist introgression between two species ,More over, D-statistic can indentify the introgression region  . But can you tell me how to judge the introgression region in detail ? To my knowledge ,the low D value or fD value refers to an introgression ,is that true ? if any, how to decide the  threshold value, and Can Chromosome-Length Alignments indentify introgression region ? Thanks for your Detailed sharing . It's appreciated if you can illuminate my question.

**Comment by mmatschiner** [comment]
The introgressed region should have elevated D or fd. In principle, the identification of such regions is possible with chromosome-length alignments; however, in practice, the patterns are usually not very clear. But just check the fd in sliding-windows (and test different window sizes) and you will see how clear or ambiguous the introgression patterns  are in your dataset.
