### ISSUE TITLE
How to calculate standard deviation base on 95% HPD interval?

### ISSUE THREAD

**Issue by xiekunwhy** [mmatschiner/tutorials#11]
Hi,

In <Divergence-Time Estimation with SNP Data> tutorial, you said that "the divergence of Astatotilapia burtoni ("astbur") and the Neolamprologus species was estimated at 6.2666 Ma with a 95% HPD interval from 4.8225 to 7.9049 Ma (...). We can approximate this mean and confidence interval with a lognormal distribution centered at 6.2666 Ma that has a standard deviation (in real space) of 0.13".
Can you explain the details of how to approximate the standard deviation based on the known informations?

Best,
Kun

**Comment by mmatschiner** [comment]
Hi,
this approximation is not very sophisticated. A practical approach is to plot the distribution in R or in the Prior panel in BEAUti, and to change the standard deviation until you find a value that brings the 2.5% quantile and the 97.5% quantiles of this (lognormal) distribution close to the boundaries of the previously estimated 95% HPD interval.
Cheers,
Michael

**Comment by xiekunwhy** [comment]
Hi,

Thank you for your answers, and I will try BEAUti.

Best,
kun
