### ISSUE TITLE
Why we need SNAPP to estimate divergence time?

### ISSUE THREAD

**Issue by xiekunwhy** [mmatschiner/tutorials#13]
Hi Michael,

I just curious that why we need SNAPP to estimate divergence time base on genome wide SNPs and why we can not use mcmctree or beast2 to estimate divergence time base on genome wide SNPs? Any papers discuss this question?

SNAPP is so slow when sample size is large even using a few SNPs.

Best,
Kun

**Comment by mmatschiner** [comment]
Hi Kun,

You can use this as a starting point: https://academic.oup.com/sysbio/article/67/4/681/4827616
