### ISSUE TITLE
Do you know how to use SNAPPER?

### ISSUE THREAD

**Issue by xiekunwhy** [mmatschiner/tutorials#14]
Hi,

Excellent tutorials.

I am now doing divergence time estimation using SNP data, and seems that SNAPP is the only software which can do this, but is really computationally demanding when species number is large.

I found that there is a difussion based version of SNAPP(https://github.com/rbouckaert/snapper), which can do the same thing faster, but I can't find any infomation about how to use this package and the author is busy. Do you know how to use this package? Would you please provide some materials if you know how to use.

Best,
Kun

**Comment by mmatschiner** [comment]
Hi Kun,

I've heard of SNAPPER but unfortunately have not been able to try it myself.

Best,
Michael
