### ISSUE TITLE
It seems that this species is in the SETS.txt file but can't be found in the tree. Please check the spelling and completeness of your tree file.

### ISSUE THREAD

**Issue by addefg** [mmatschiner/tutorials#15]
Hi,
I have encountered this issue while computing D among my 3 pops except the outgroup. I have a SETS.txt file of just two columns with the individuals and their pops. 
I do not understand where this error comes from
Thanks in advance
Apdu

$  ./Build/Dsuite Dtrios -c -n no_geneflow -t chr.6_fourPoPs.nwk chr.6_fourPoPs.vcf.gz sets.txt

**Comment by mmatschiner** [comment]
Hi,
you'll need to check if the names are identical between the tree and the sets.txt file. Apparently they are not.
Cheers,
Michael
