### ISSUE TITLE
How to prepare bed file for analysis_of_introgression_with_chromosome_length_alignments?

### ISSUE THREAD

**Issue by Chenglin20170390** [mmatschiner/tutorials#16]
Hi, Can you tell me the details about how to prepare bed file for analysis_of_introgression_with_chromosome_length_alignments? I have done the tutorials, but I can not find a pattern from your example data(individual vcf/ masked file).

**Comment by mmatschiner** [comment]
Hi,

That's a bit difficult to explain. The map is a combination of three different maps that are based on the read depths, the distance to indels, and mappability to the reference genome. All scripts used can be found here: https://github.com/cichlidx/ronco_et_al/blob/master/variant_calling/src
The script that ultimately produces the bed file is this merge_all_masks_all_samples.sh, but it uses data that has been prepared with many other scripts. An overview of the order in which the scripts were executed can be found in run_all.sh in that directory.

**Comment by Chenglin20170390** [comment]
Hi Matschiner,

Many thanks for your quick response with a detailed explanation.  That's really helpful~~

thanks~
