### ISSUE TITLE
raise NewickError('Unexisting tree file or Malformed newick tree structure.')

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [mmatschiner/tutorials#17]
its a error, when I run the script,
![image](https://user-images.githubusercontent.com/101324838/164406654-dbc2e6b6-c1e9-417c-9f67-28d9d34cc726.png)
![image](https://user-images.githubusercontent.com/101324838/164406739-d127076f-bd75-4437-aa45-737c9efca326.png)

**Comment by Jiangjiangzhang6** [comment]
hello, my friend, when I run the script for plot with my own data set, its showed that the format or quoted_node_names,
![image](https://user-images.githubusercontent.com/101324838/164407379-e2c60d52-0ab0-414a-8945-92c2e63f9fc8.png)

**Comment by mmatschiner** [comment]
Yes, it seems you’re not providing the input that the Dsuite Fbranch function requires.

**Comment by Jiangjiangzhang6** [comment]
Hello, could you point the detail , "Dsuite Fbranch function requires.", but I run the "Dsuite Fbranch Newick sets_tree.txt >species_sets_with_geneflow_Fbranch.txt", and this process was done, and the 
![image](https://user-images.githubusercontent.com/101324838/164408900-79d1a4c1-52ec-454c-85fa-04f7cc689a47.png)
the file was exit, Dear friend, how to debug? thank you

**Comment by Jiangjiangzhang6** [comment]
my newick tree file was the file "Newick"

**Comment by mmatschiner** [comment]
I recommend to contact the lead author of Dsuite, Milan Malinsky.

**Comment by mmatschiner** [comment]
I recommend to contact the lead author for Dsuite, Milan Malinsky.
