### ISSUE TITLE
FFT algorithm

### ISSUE THREAD

**Issue by ASQWZXED** [mmatschiner/tutorials#18]
Dears,

I want to understand MAFFT before choosing it to align my data.
I understand that it apply FFT algorithm before pairwise alignment, is that right ?  Also, what is the expected reduction of the sequence length after applying FFT and before applying pairwise alignment?

I wish you answer my questions.
Thank you in  advance.

**Comment by mmatschiner** [comment]
Please address this question to the authors of MAFFT. This repository merely uses MAFFT.

**Comment by ASQWZXED** [comment]
Thank you
