### ISSUE TITLE
Are there any references to the testing of trios topology asymmetry? 

### ISSUE THREAD

**Issue by sy-snake** [mmatschiner/tutorials#4]
How to cite the method that testing trios topology asymmetry?

**Comment by mmatschiner** [comment]
Hi, if you mean the part in section "Analyzing asymmetry of trio topologies" with the heatmap type of plots, we're about to submit a manuscript that presents this method. But before that is public, it might be best to cite the github website for the tutorial.
If you mean the part in section "Genome-wide genealogy interrogation" with the triangular plots, you could cite the Barth et al. bioRxiv preprint at https://www.biorxiv.org/content/10.1101/635631v1
That manuscript is about to be resubmitted after revision.
