### ISSUE TITLE
ruby plot_d.rb script arguments and output

### ISSUE THREAD

**Issue by vsoza** [mmatschiner/tutorials#9]
Hi
I would like to use the ruby plot_d.rb script to generate a heatmap of D-statistics from D-suite. I have 2 questions regarding the script after going through the tutorial.

1) How do we determine the maximum D-value to use as an argument for this script? Do we select this based on our dataset or is 0.7 a good value to use as a default/threshold?

2) What do the cells in the heatmap represent: the most significant D-statistic or the maximum D-value for a pair of species?

Thanks!

**Comment by mmatschiner** [comment]
Hi,
There's nothing special about the value 0.7. You could use any other, but it makes sense to set it close to the maximum D value that you find in the output files of Dsuite.
And the result shown per cell is the one with the most significant D-statistic per pair.

**Comment by vsoza** [comment]
Thank you, Michael, for clarifying this!
